"""Build the RAG knowledge base from backend/data/knowledge/*.json.

Strategy: atomic chunking — each bullet point, project, and skill category gets
its own document so retrieval is precise rather than scanning large blobs.
Also includes synthesized FAQ documents that pre-answer common recruiter questions.

Hash-based smart re-ingest: on startup, SHA256 of all knowledge JSON files is
compared against the stored hash in chroma_db/.ingest_hash. If changed (or no
hash exists), the collection is wiped and rebuilt. This means any commit that
updates JSON files automatically triggers a full re-ingest on the next deploy.
"""

import hashlib
import json
import logging
from pathlib import Path

from app.rag.store import build_bm25_index, get_collection, reset_collection

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).parents[3] / "data" / "knowledge"

# ── Content hash helpers ───────────────────────────────────────────────────────

def _hash_file() -> Path:
    from app.core.settings import settings
    return Path(settings.chroma_db_path) / ".ingest_hash"


def _compute_content_hash() -> str:
    h = hashlib.sha256()
    for f in sorted(DATA_DIR.glob("*.json")):   # alphabetical = deterministic
        h.update(f.read_bytes())
    return h.hexdigest()


def _read_stored_hash() -> str:
    try:
        return _hash_file().read_text().strip()
    except FileNotFoundError:
        return ""


def _write_stored_hash(digest: str) -> None:
    p = _hash_file()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(digest)


# ── Document loaders ───────────────────────────────────────────────────────────

def _load(filename: str) -> dict | list | None:
    path = DATA_DIR / filename
    if not path.exists():
        logger.warning("Missing knowledge file: %s", path)
        return None
    return json.loads(path.read_text())


def _build_blog_documents() -> list[tuple[str, str, str]]:
    """Build one chunk per blog post from blog.json (generated by scripts/sync-knowledge.mjs)."""
    path = DATA_DIR / "blog.json"
    if not path.exists():
        return []
    docs = []
    for post in json.loads(path.read_text()):
        slug = post.get("slug", "unknown")
        title = post.get("title", "")
        date = post.get("date", "")
        desc = post.get("description", "")
        tags = ", ".join(post.get("tags", []))
        body = post.get("content", "")
        docs.append((
            f"blog_{slug}",
            f"Blog post by Jaya: '{title}' (published {date}). {desc} Tags: {tags}. {body}",
            "blog",
        ))
    return docs


def _build_lab_documents() -> list[tuple[str, str, str]]:
    """Build one chunk per lab entry from lab.json (generated by scripts/sync-knowledge.mjs)."""
    path = DATA_DIR / "lab.json"
    if not path.exists():
        return []
    docs = []
    for entry in json.loads(path.read_text()):
        slug      = entry.get("slug", "unknown")
        title     = entry.get("title", "")
        status    = entry.get("status", "")
        desc      = entry.get("description", "")
        tech      = ", ".join(entry.get("tech", []))
        started   = entry.get("startedAt", "")
        updated   = entry.get("updatedAt", "")
        body      = entry.get("content", "")
        docs.append((
            f"lab_{slug}",
            (
                f"Lab project by Jaya: '{title}' (status: {status}, started {started}, "
                f"last updated {updated}). {desc} Tech stack: {tech}. {body}"
            ),
            "lab",
        ))
    return docs


def _build_documents() -> list[tuple[str, str, str]]:
    """Return list of (id, text, type) tuples — atomic chunks for precise retrieval."""
    docs: list[tuple[str, str, str]] = []

    # ── PROFILE ──────────────────────────────────────────────────────────────
    p = _load("profile.json")
    if p:
        docs.append(("profile_overview", (
            f"Jaya Sabarish Reddy Remala is a {p['tagline']}. "
            f"{p.get('summary', p['bio'])} "
            f"He is based in {p['location']}."
        ), "profile"))

        docs.append(("profile_bio", (
            f"About Jaya: {p['bio']}"
        ), "profile"))

        docs.append(("profile_contact", (
            f"Jaya's contact information — "
            f"Email: {p['email']}, "
            f"Phone: {p['phone']}, "
            f"GitHub: {p['github']}, "
            f"LinkedIn: {p['linkedin']}, "
            f"Location: {p['location']}. "
            f"Resume: {p.get('resume', '')}."
        ), "profile"))

    # ── EXPERIENCE ────────────────────────────────────────────────────────────
    exp_list = _load("experience.json")
    if exp_list:
        for i, e in enumerate(exp_list):
            company = e["company"]
            role = e["role"]
            period = f"{e['start']} – {e['end']}"
            tech = e.get("tech", "")

            docs.append((f"exp_{i}_overview", (
                f"Jaya worked as {role} at {company} ({period}). "
                f"{e.get('description', '')} "
                f"Technologies used: {tech}."
            ), "experience"))

            for j, bullet in enumerate(e.get("bullets", [])):
                docs.append((f"exp_{i}_bullet_{j}", (
                    f"At {company} as {role} ({period}): {bullet}"
                ), "experience"))

    # ── EDUCATION ─────────────────────────────────────────────────────────────
    edu_list = _load("education.json")
    if edu_list:
        for i, e in enumerate(edu_list):
            institution = e["institution"]
            school = e.get("school", "")
            full_institution = f"{institution}, {school}" if school else institution
            degree = f"{e['degree']} in {e['field']}"
            period = f"{e['start']} – {e['end']}"
            gpa = e.get("gpa", "")

            docs.append((f"edu_{i}_overview", (
                f"Jaya studied {degree} at {full_institution} ({period}). "
                f"{'GPA: ' + gpa + '.' if gpa else ''}"
            ), "education"))

            for j, h in enumerate(e.get("highlights", [])):
                docs.append((f"edu_{i}_highlight_{j}", (
                    f"At {full_institution}: {h}"
                ), "education"))

    # ── PROJECTS ──────────────────────────────────────────────────────────────
    proj_list = _load("projects.json")
    if proj_list:
        for i, proj in enumerate(proj_list):
            title = proj["title"]
            tags = ", ".join(proj.get("tags", []))
            award = proj.get("award", "")
            award_str = f" This project won the {award}." if award else ""

            docs.append((f"proj_{i}_overview", (
                f"Project: {title}.{award_str} {proj['description']}"
            ), "project"))

            docs.append((f"proj_{i}_tech", (
                f"Technologies used in {title}: {tags}."
                f"{' Award: ' + award if award else ''}"
            ), "project"))

    # ── SKILLS ────────────────────────────────────────────────────────────────
    skills_list = _load("skills.json")
    if skills_list:
        for group in skills_list:
            category = group["category"]
            items = ", ".join(group["items"])
            slug = category.lower().replace(" ", "_").replace("&", "and")
            docs.append((f"skills_{slug}", (
                f"Jaya's {category} skills: {items}."
            ), "skills"))

        all_items = [item for g in skills_list for item in g["items"]]
        docs.append(("skills_all", (
            f"Jaya's full technical skill set spans: {', '.join(all_items)}."
        ), "skills"))

    # ── BLOG POSTS ────────────────────────────────────────────────────────────
    docs.extend(_build_blog_documents())

    # ── LAB ENTRIES ───────────────────────────────────────────────────────────
    docs.extend(_build_lab_documents())

    # ── SYNTHESIZED FAQ DOCUMENTS ─────────────────────────────────────────────

    docs.append(("faq_who", (
        "Who is Jaya Sabarish Reddy Remala? Jaya is a Software Engineer with 3+ years of "
        "experience building production AI infrastructure and distributed systems. "
        "He won the Qualcomm Edge AI Hackathon, holds an MS in Computer Science from NYU Tandon "
        "(GPA 3.8/4.0), and has built systems handling 3,000+ RPS at 99.9% uptime. "
        "He specializes in Agentic AI, RAG pipelines, LLM inference optimization, and "
        "fault-tolerant distributed microservices."
    ), "faq"))

    docs.append(("faq_strengths", (
        "What makes Jaya stand out as an engineer? Key differentiators: "
        "(1) Won Qualcomm Edge AI Hackathon by achieving 15ms LLM inference on Snapdragon NPUs — "
        "10× faster than cloud inference — using QLoRA fine-tuning and AWQ quantization. "
        "(2) Cut RAG P99 latency by 78% (450ms → under 100ms) on a production system at 3K+ RPS. "
        "(3) Built zero-data-loss maritime telemetry for Shell PLC — 115GB/day, 200+ offshore stations. "
        "(4) Full-stack AI expertise from Edge NPU inference to distributed LangGraph multi-agent systems."
    ), "faq"))

    docs.append(("faq_experience_summary", (
        "Jaya's work experience summary: Software Engineer at NYU College of Arts and Science (Jun 2025–Present) "
        "building GeneCart genomics platform. Web Applications Lead at NYU IT (Sep 2024–May 2025) leading a "
        "production Multi-Agent Research Discovery Engine. Software Engineer Intern at NYU IT (May–Aug 2024) "
        "building high-concurrency distributed search infrastructure. Teaching Assistant at NYU (Sep 2024–May 2025) "
        "for Data Structures & Algorithms and ML for Bioinformatics. Software Engineer at Wipro/Shell PLC "
        "(Jul 2021–Feb 2023) building fault-tolerant maritime energy infrastructure. "
        "Full Stack Developer at VIT (Jan–Jun 2021) building gradeVITian serving 17K+ users."
    ), "faq"))

    docs.append(("faq_projects_summary", (
        "Jaya's notable projects: "
        "SnapLog (Qualcomm Edge AI Hackathon Winner) — 15ms LLM inference on Snapdragon NPUs via QLoRA + AWQ. "
        "CodeCollab — real-time collaborative code editor with CRDTs, AI auto-complete, scaled with Nginx. "
        "Multi-Agent Research Discovery Engine — LangGraph + Llama 3.1 70B, 3K+ RPS, 78% latency reduction. "
        "GeneCart — AI-powered genomics discovery platform at NYU (in progress). "
        "gradeVITian — grade forecasting PWA, 17K+ monthly users, #2 Google Search ranking."
    ), "faq"))

    docs.append(("faq_education_summary", (
        "Jaya's education: Master of Science in Computer Science from NYU Tandon School of Engineering "
        "(Aug 2023 – May 2025, GPA 3.8/4.0). Coursework includes Distributed Systems, Machine Learning, "
        "Design and Analysis of Algorithms, and Operating Systems. "
        "Bachelor of Technology in Electrical and Electronics Engineering from Vellore Institute of Technology "
        "(Jul 2017 – May 2021)."
    ), "faq"))

    docs.append(("faq_awards", (
        "Jaya's awards and recognition: Won the Qualcomm Edge AI Hackathon with SnapLog — "
        "an on-device security AI engine achieving 15ms inference on Snapdragon NPUs. "
        "Received the Outstanding Inclusivity Initiative award as Head of Operations at NYU Graduate Indian Student Association."
    ), "faq"))

    docs.append(("faq_ai_expertise", (
        "Jaya's AI and machine learning expertise: LangGraph multi-agent orchestration, RAG pipeline optimization, "
        "LLM fine-tuning with QLoRA, AWQ 4-bit quantization, ONNX Runtime deployment, Edge AI on Snapdragon NPUs, "
        "BGE-M3 dense embeddings, Reciprocal Rank Fusion (RRF) for retrieval, "
        "Voyage AI code embeddings, PyTorch, Llama 3.1 70B, Llama 3.2 3B, Claude 3.5."
    ), "faq"))

    docs.append(("faq_distributed_systems", (
        "Jaya's distributed systems expertise: horizontally-scaled async pipelines on AWS ECS with Kubernetes, "
        "Apache Kafka for fault-tolerant streaming (115GB/day), Redis Write-Through caching sustaining 3K+ RPS "
        "at sub-millisecond retrieval, circuit-breaker patterns for 99.9% uptime, "
        "zero-downtime rolling deployments with CI/CD, AsyncIO for parallel data fetching, "
        "event-driven Apex Async Micro-functions at Wipro/Shell."
    ), "faq"))

    docs.append(("faq_contact_hire", (
        "How to contact or hire Jaya Sabarish Reddy Remala: "
        "Email: jr6421@nyu.edu, Phone: +1 (516) 907-8727, "
        "LinkedIn: https://linkedin.com/in/jayasabarishreddyr, "
        "GitHub: https://github.com/sabarishreddy99. "
        "He is based in New York, NY and open to relocation."
    ), "faq"))

    docs.append(("faq_resume", (
        "Jaya's resume / CV is available at: "
        "https://drive.google.com/drive/u/0/folders/1vm35z-6VQjtO9A8ZBgCvvSP_7_POPTrV — "
        "You can download or view his full resume there. "
        "For direct contact: jr6421@nyu.edu or +1 (516) 907-8727."
    ), "faq"))

    docs.append(("faq_nyu_work", (
        "What did Jaya do at NYU? Jaya had three roles at NYU: "
        "As Web Applications Lead at NYU IT (2024–2025), he architected a production Multi-Agent Research Discovery Engine "
        "using LangGraph and Llama 3.1 70B, reducing RAG latency by 78% and sustaining 3K+ RPS. "
        "As a Software Engineer Intern at NYU IT (Summer 2024), he built FastAPI microservices on AWS ECS "
        "with AsyncIO parallel fetching and Redis caching. "
        "As a Software Engineer at NYU CAS (2025–Present), he is building GeneCart, "
        "an AI-assisted genomics discovery platform."
    ), "faq"))

    docs.append(("faq_shell_wipro", (
        "What did Jaya do at Wipro and Shell? Jaya was embedded at Shell PLC via Wipro (Jul 2021–Feb 2023). "
        "He built a fault-tolerant Apache Kafka pipeline processing 115GB/day across 200+ offshore crude oil stations in Brazil "
        "with zero data loss. He also reduced support tickets by 35% via a Self-Service Portal, "
        "increased fault tolerance by 39% by decomposing a Salesforce monolith into event-driven micro-functions, "
        "and reduced production incidents by 25% with a defensive ETL validation layer."
    ), "faq"))

    docs.append(("faq_blog", (
        "Jaya writes on his blog at jayaremala.com/blog. "
        "Topics include software engineering, AI, personal reflections, and career insights."
    ), "faq"))

    docs.append(("faq_lab", (
        "Jaya publishes living system design documentation in the Lab section at jayaremala.com/lab. "
        "Lab entries document active projects with architecture diagrams, key technical decisions, "
        "progress logs, and the reasoning behind design choices — updated as projects evolve."
    ), "faq"))

    docs.append(("faq_portfolio_how_it_works", (
        "How does this portfolio work? How is Avocado built? "
        "jayaremala.com is Jaya's AI-powered portfolio. It has two parts: "
        "(1) Avocado — a full-screen RAG-powered AI chatbot at the homepage that answers questions about Jaya in real time. "
        "(2) A classic portfolio with experience, projects, education, blog, and a lab section. "
        "Avocado works like this: when you type a question, the backend runs a 4-stage hybrid retrieval pipeline — "
        "query expansion (up to 4 variants), dense search via ChromaDB (all-MiniLM-L6-v2 ONNX embeddings), "
        "lexical search via BM25 (catches exact names, numbers, company names), "
        "Reciprocal Rank Fusion to merge results, then the top 5 chunks are injected into Gemini's system prompt "
        "and the response streams token-by-token back to the browser via Server-Sent Events. "
        "The chatbot is production-grade — streaming tokens, hybrid retrieval, model fallback chain, "
        "and a knowledge base of ~80 atomic documents covering every role, project, skill, and FAQ."
    ), "faq"))

    docs.append(("faq_services_connected", (
        "How are the services connected in this portfolio? What is the system architecture? "
        "The portfolio has three layers: "
        "(1) Frontend: Next.js 16 static export hosted on GitHub Pages at jayaremala.com. "
        "No server-side rendering — fully static HTML/CSS/JS served from GitHub's CDN for free. "
        "(2) Backend API: FastAPI (Python) running in Docker on AWS Lightsail 2GB VPS at api.jayaremala.com. "
        "Nginx sits in front as a reverse proxy (port 443 → Docker port 8000) with Let's Encrypt HTTPS. "
        "(3) External AI: Google Gemini API for LLM responses. "
        "The frontend calls the backend directly from the browser — no middleman. "
        "The backend talks to Gemini over HTTPS and streams tokens back to the browser via SSE. "
        "All data (blog views, claps, chat analytics) is stored in SQLite on the Lightsail SSD at /data/analytics.db, "
        "backed up daily to Amazon S3 with 7-day retention. "
        "ChromaDB vector database persists at /data/chroma_db and auto-rebuilds from knowledge JSON on deploy if the content hash changed."
    ), "faq"))

    docs.append(("faq_rag_pipeline", (
        "How does Avocado retrieve information? What RAG pipeline does it use? "
        "Avocado uses a 4-stage hybrid RAG pipeline: "
        "Stage 1 — Query Expansion: the user message is expanded into up to 4 query variants "
        "(verbatim, name-anchored, topic keyword, conversation context) to catch different phrasings. "
        "Stage 2a — Dense retrieval: all 4 queries are embedded in a single batched ONNX forward pass "
        "using all-MiniLM-L6-v2 via fastembed, then searched against ChromaDB using HNSW cosine similarity. "
        "Stage 2b — Lexical retrieval: BM25 (rank_bm25 BM25Okapi) catches exact keyword matches — "
        "specific numbers like '3000 RPS', company names like 'Qualcomm', project names like 'SnapLog'. "
        "Stage 3 — Reciprocal Rank Fusion: merges dense and lexical results using RRF (k=60, Cormack 2009). "
        "Stage 4 — Top 5 by RRF score injected into Gemini's system prompt as context. "
        "The knowledge base has ~80 atomic documents: each bullet point, project, and skill category is its own chunk "
        "so retrieval is precise rather than returning noisy large blobs."
    ), "faq"))

    docs.append(("faq_tech_choices_tradeoffs", (
        "What technology choices did Jaya make for this portfolio and why? What are the trade-offs? "
        "Key decisions and trade-offs: "
        "(1) fastembed ONNX instead of PyTorch sentence-transformers — saves ~600MB RAM, no GPU needed, "
        "runs on a $10/month VPS. Trade-off: slightly less flexible than full PyTorch. "
        "(2) ChromaDB + BM25 hybrid instead of pure dense search — BM25 catches exact keyword matches "
        "(numbers, names) that dense search misses. Trade-off: BM25 index is in-memory, rebuilt on every startup (~5ms). "
        "(3) SQLite instead of managed Postgres for analytics — zero cost, same-process, one file to back up. "
        "Trade-off: not suitable for concurrent writers, but the single Docker container has no concurrency issue. "
        "(4) Static Next.js export on GitHub Pages instead of Vercel/SSR — free, CDN-served, no cold starts. "
        "Trade-off: no server-side rendering, all dynamic data fetched client-side. "
        "(5) AWS Lightsail $10/month instead of Railway PaaS — persistent SSD storage, full control, no trial limits. "
        "Trade-off: more DevOps responsibility (Docker, Nginx, Certbot, backups). "
        "(6) Gemini 2.5 Flash with fallback chain instead of a single model — high availability even at peak times. "
        "Trade-off: response quality varies slightly across fallback models. "
        "(7) 12 hard-coded FAQ documents — highest ROI for recruiter query quality. "
        "Trade-off: must be manually updated as achievements change."
    ), "faq"))

    docs.append(("faq_deployment_cicd", (
        "How is the portfolio deployed? What is the CI/CD pipeline? "
        "Everything deploys automatically on every git push to main via GitHub Actions: "
        "(1) Frontend: npm build runs sync-knowledge.mjs (generates blog.json from MDX posts), "
        "then Next.js builds a static export to frontend/out/, which is uploaded to GitHub Pages at jayaremala.com. "
        "(2) Backend: GitHub Actions SSHes into AWS Lightsail and runs infra/scripts/deploy.sh — "
        "a zero-downtime blue-green deployment script. It builds the new Docker image, "
        "starts it on port 8001, health-checks it for up to 120 seconds (ONNX model warmup), "
        "then swaps to port 8000 only if the health check passes. "
        "If the new container fails health check, the old container keeps running — zero downtime. "
        "The previous Docker image is tagged :previous for instant rollback with one command. "
        "Analytics data is backed up daily to S3 and auto-restored from S3 if missing on a fresh instance. "
        "The total monthly cost is $10 for Lightsail — the frontend, CI/CD, and SSL are all free."
    ), "faq"))

    docs.append(("faq_data_persistence", (
        "How is data stored and protected in this portfolio? "
        "All analytics data (blog views, claps, Avocado chat stats) lives in a single SQLite file "
        "at /data/analytics.db on the AWS Lightsail 60GB SSD. "
        "IPs are SHA-256 hashed before storage — never stored raw, privacy-preserving by design. "
        "The file is backed up daily at 02:00 UTC to Amazon S3 (itsjaya-backups-analytics bucket) "
        "with 7 days of timestamped history kept automatically. "
        "On every deploy, if /data/analytics.db is missing (e.g. fresh instance after disaster), "
        "the deploy script automatically restores the latest backup from S3 before starting the container. "
        "ChromaDB (the vector database) does not need backup — it is fully rebuilt from the knowledge JSON files "
        "on every deploy when the content hash changes. Docker logs are rotated automatically: "
        "json-file driver, 10MB max per file, 3 files kept."
    ), "faq"))

    docs.append(("faq_portfolio_vs_standard", (
        "How is this portfolio different from a standard portfolio website? "
        "A standard portfolio is a one-way broadcast — you decide what to highlight, the visitor reads it, done. "
        "The visitor's actual question ('does he have Redis caching experience?') rarely aligns with what's on the page. "
        "This portfolio inverts the model: the visitor asks in natural language, the RAG system retrieves "
        "the most relevant evidence from Jaya's actual experience, and Gemini synthesises a grounded answer. "
        "Every claim Avocado makes is backed by a retrieved document from the knowledge base — "
        "not hallucinated. The knowledge base is the resume; Avocado is the interface. "
        "Additionally, the blog has real engagement tracking (views, claps), the lab section has living "
        "system design documentation updated as the project evolves, and the entire system auto-deploys "
        "on every git push with zero manual steps."
    ), "faq"))

    docs.append(("faq_knowledge_base", (
        "What is in Avocado's knowledge base? What can it answer questions about? "
        "The knowledge base has approximately 80 atomic documents across 8 types: "
        "Profile (3 docs): overview, bio, contact information. "
        "Experience (~25 docs): one overview per role + one document per bullet point per job. "
        "Education (~10 docs): one overview per degree + one per highlight. "
        "Projects (~14 docs): one overview + one tech-stack doc per project. "
        "Skills (8 docs): one per category + one aggregated. "
        "FAQ (12 docs): handwritten answers to the highest-probability recruiter questions — "
        "contact info, hiring, strengths, resume link, specific achievements with exact numbers. "
        "Blog: one document per published blog post. "
        "Lab: one document per lab entry. "
        "Avocado can answer questions about work history, projects, skills, education, awards, "
        "contact information, resume, blog posts, and how this portfolio itself is built."
    ), "faq"))

    return docs


def run_ingest(force: bool = False) -> int:
    """Ingest knowledge base into ChromaDB. Re-ingests automatically when content hash changes.

    Hash is stored at chroma_db/.ingest_hash (same persistent volume as ChromaDB on Railway).
    Any deploy that commits new/updated JSON files will trigger a full re-ingest on startup.
    """
    current_hash = _compute_content_hash()
    stored_hash = _read_stored_hash()
    collection = get_collection()
    docs = _build_documents()   # always build — BM25 needs it regardless

    content_changed = current_hash != stored_hash
    db_empty = collection.count() == 0

    if not force and not content_changed and not db_empty:
        logger.info("Content hash unchanged — skipping re-ingest (%d docs in DB)", collection.count())
        build_bm25_index(docs)
        return collection.count()

    reason = "forced" if force else ("hash changed" if content_changed else "empty DB")
    logger.info("Re-ingesting knowledge base (%s, hash: %s→%s)...",
                reason, stored_hash[:8] or "none", current_hash[:8])
    reset_collection()
    collection = get_collection()

    if not docs:
        logger.warning("No knowledge documents found in %s", DATA_DIR)
        return 0

    ids = [d[0] for d in docs]
    texts = [d[1] for d in docs]
    metadatas = [{"type": d[2], "id": d[0]} for d in docs]

    collection.upsert(ids=ids, documents=texts, metadatas=metadatas)
    build_bm25_index(docs)
    _write_stored_hash(current_hash)
    logger.info("Ingested %d documents (hash: %s)", len(docs), current_hash[:12])
    return len(docs)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    count = run_ingest(force=True)
    print(f"Ingested {count} documents.")
